# Generated by Django 4.0.2 on 2022-05-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songAuthor', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr', models.CharField(max_length=999)),
                ('description', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songname', models.CharField(max_length=999)),
                ('description', models.CharField(max_length=999)),
                ('janr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='spotify.janr')),
                ('songAuthor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='spotify.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='janr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='spotify.janr'),
        ),
    ]
