# Generated by Django 4.0.2 on 2022-05-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='songAuthor',
            new_name='Authors',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songAuthor',
            new_name='Authors',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songname',
            new_name='song',
        ),
    ]
