# Generated by Django 4.0.2 on 2022-05-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_songauthor_author_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='description',
        ),
    ]
